### ISSUE TITLE
[Help] Development environment setup

### ISSUE THREAD

**Issue by dobrishinov** [mrlima4095/OpenTTY-J2ME#1]
Hey, great app!
I'm also interested on the j2me development.
Can you share more information how you setup the development environment?
Which NetBeans and libraries you're using? Any help will be helpful because most of the sources about the j2me is too old and most of the links are pointing to nothing now a days.
Here is my email address also if you want to talk more - dobrishinov@gmail.com
Best Regards!

**Comment by mrlima4095** [comment]
Hi, thanks! I don't have a computer, I use an application for J2ME which is an SDK that I can compile the code for Jar from it. I can send it in your email if you want...

**Comment by dobrishinov** [comment]
Great thanks, I appreciate! So you compile the project directly on the phone? Please share the name of the sdk and the file on my email. Want to try to build also the project and to experiment to write some other apps. Thanks!

**Comment by app4soft** [comment]
Could you share (upload somewhere or give a link) to your _J2ME SDK Mobile 1.1.0_ JAR-file?

**Comment by mrlima4095** [comment]
https://phoneky.com/games/?id=j4j73348

**Comment by guhikl** [comment]
why can't the jar be made public?

**Comment by mrlima4095** [comment]
you can download J2ME SDK Mobile on [this link](http://opentty.xyz/dl/SDK.jar)

**Comment by guhikl** [comment]
yeah i'm aware but i can't compile it since i get java.lang.OutOfMemoryError BUILD FAILED on my phone
